# Build settings

source: .
destination: ./_site
markdown: kramdown
# don't change the following; coderay will break the embedded
# annotations.
kramdown:
  enable_coderay: false
permalinks: pretty
# safe: true
markdown_ext: md

##############################################################################

# Site settings

title: Constructions in CCG
baseurl: "/ccg-cxns"
homeurl: "https://github.com/nschneid/ccg-cxns/"
editurl: "https://github.com/nschneid/ccg-cxns/edit/gh-pages"
issueurl: "https://github.com/nschneid/ccg-cxns/issues"

##############################################################################

# Collection settings

collections:
  entity:
    output: false
  relation:
    output: false
  mwe:
    output: true
